spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t9w2TCVmRrvySny7PNd
      secret-key: 5Fev8UR0abYzB0uUm8Ogej3Z06xju0
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: liujiangang-ljg

  application:
    name: gulimall-third-party

server:
  port: 30000
